export enum ActionTypes {
  UPDATE_CELL = "UPDATE_CELL",
  DELETE_CELL = "DELETE_CELL",
  INSERT_BEFORE_CELL = "INSERT_BEFORE_CELL",
  MOVE_CELL = "MOVE_CELL",
  FETCH_CELL = "FETCH_CELL",
  BUNDLE_START = "BUNDLE_START",
  BUNDLE_COMPLETE = "BUNDLE_COMPLETE",
}
